version: "2"
services:
  web:
    image: rlkamradt/my-react-app:latest
    networks:
      - network
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ~/.certs:/etc/certs
    ports:
     - "443:443"
  redis:
    image: redis:alpine
    networks:
      - network
  api:
    image: rlkamradt/my-express-app:latest
    networks:
      - network
networks:
  network:
